spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    platform: org.hibernate.dialect.H2Dialect
    url: jdbc:h2:file:D:/theatre/data/theatredb
  jpa:
    hibernate:
      ddl-auto: create